name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, development ]

env:
  DATABASE_USER: ${{secrets.DATABASE_USER}} 
  DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
  DATABASE_HOST: ${{secrets.DATABASE_HOST}}
  bearer_token: ${{secrets.BEARER_TOKEN}}
  consumer_key: ${{secrets.CONSUMER_KEY}}
  consumer_secret: ${{secrets.CONSUMER_SECRET}}
  access_token: ${{secrets.ACCESS_TOKEN}}
  access_token_secret: ${{secrets.ACCESS_TOKEN_SECRET}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: backend # Path to the top-level backend folder containing the Python env
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: backend/django_site # Path to the Django folder
      run: |
        python manage.py test --keepdb
